[package]
name = "ji"
version = "0.1.0"
authors = ["Micah Johnston <micah@glowcoil.com>"]
edition = "2018"

[dependencies]
gl = "0.11.0"
glutin = "0.19.0"
font-rs = { git = "https://github.com/raphlinus/font-rs" }
lyon = "0.13.1"
