[package]
name = "ji"
version = "0.1.0"
authors = ["Micah Johnston <micah@glowcoil.com>"]
edition = "2018"

[dependencies]
gl = "0.11.0"
glutin = "0.19.0"

[dependencies.nanovg]
version = "1.0.2"
features = ["gl3"]

[profile.release]
lto = true
panic = 'abort'
